# Site settings 配置站点
title: 'Minha Portfolio'
description: 'JAVA WEB DEVELOPER'
keywords: '성실함, 그리고 꾸준함'
url: 'https://minhaHwnag.github.io/' # your host

# nav：&emsp;
nav: 
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'Minha Hwang'
NickName: 'Elliot Hwang'
webtitle: 'Portfolio'
bio: 'your awesome bio'
about: true
aboutyou: 'Minha?'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'minha0616@gmail.com'
  weixin: '' # 你的微信二维码存放的地址
  qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: ''
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# rouge
highlighter: rouge
# autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 
pygmentsTheme: 'default'

#friends:
#  jekyll: 'https://www.jekyll.com.cn/'

#disqus、livere Gitment
# disqus 
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
#
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment  OAuth Application
Gitment: false
Gitment_owner: ''  # githu
Gitment_repo: ''  # github
client_id: ''  #  OAuth Application client_id
client_secret: ''  # OAuth Application client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

#
baidu: true
baidu-url: ''
#
google: false
google-ID: ''

#
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
